"use client";
import { useMemo, useState } from "react";
import { ArrowRight, Bookmark, CalendarPlus, Check, CloudRain, Clock3, Compass, MapPin, Search, Sparkles, Users, X } from "lucide-react";
import { experiences } from "@/lib/data";
import { parseTravelIntent } from "@/lib/ai";
import { recommend } from "@/lib/recommendations";
import { TravelerContext } from "@/lib/types";

const initial:TravelerContext={budget:1500,timeAvailable:180,groupSize:3,interests:["food","culture","hidden gem"],maxDistance:6,accessibility:["step-free"],isRaining:false,travelerType:"family",strictBudget:false};
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);
export default function DiscoveryApp(){
 const [ctx,setCtx]=useState(initial),[query,setQuery]=useState("I have 3 hours in Mumbai and want something local with my family under ₹1500"),[saved,setSaved]=useState<string[]>([]),[plan,setPlan]=useState<string[]>([]),[provider,setProvider]=useState(false),[toast,setToast]=useState("");
 const results=useMemo(()=>recommend(experiences,ctx).slice(0,6),[ctx]); const update=(p:Partial<TravelerContext>)=>setCtx(c=>({...c,...p}));
 function run(){const p=parseTravelIntent(query); update({...p,interests:p.interests?.length?p.interests:ctx.interests}); setToast("Intent understood — recommendations refreshed"); setTimeout(()=>setToast(""),2500);}
 const add=(id:string)=>{if(!plan.includes(id))setPlan([...plan,id]);setToast("Added to your itinerary · 7:00 PM");setTimeout(()=>setToast(""),2500)};
 if(provider)return <Provider onBack={()=>setProvider(false)}/>;
 return <main><nav><div className="brand"><Compass size={21}/> roamly</div><div className="navlinks"><span className="active">Discover</span><span>Itinerary <b>{plan.length}</b></span><span>Saved <b>{saved.length}</b></span><button className="providerBtn" onClick={()=>setProvider(true)}>Provider view <ArrowRight size={15}/></button></div></nav>
 <section className="hero"><div className="eyebrow"><Sparkles size={14}/> FEASIBILITY-FIRST DISCOVERY</div><h1>Make the most of<br/><i>the time you have.</i></h1><p>Local experiences that understand your real-world constraints — not just your search terms.</p>
 <div className="search"><Search size={21}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&run()}/><button onClick={run}>Find experiences <ArrowRight size={17}/></button></div>
 <div className="quick"><button onClick={()=>update({timeAvailable:90})}><Clock3/> Only 90 min</button><button onClick={()=>update({isRaining:true})}><CloudRain/> Rain started</button><button onClick={()=>update({budget:800})}>₹ Budget ₹800</button><button onClick={()=>update({maxDistance:2})}><MapPin/> Closer options</button></div></section>
 <section className="context"><div><span>Your current plan</span><strong>Mumbai · Bandra hotel</strong></div><div><Clock3/><span><b>{ctx.timeAvailable} min</b> available</span></div><div><Users/><span><b>{ctx.groupSize} people</b> · {ctx.travelerType}</span></div><div><span><b>{money(ctx.budget)}</b> per-person budget</span></div><div className={ctx.isRaining?"rain yes":"rain"}><CloudRain/><span>{ctx.isRaining?"Rain context on":"Clear conditions"}</span></div></section>
 <section className="pipeline"><div><b>36</b><span>candidates found</span></div><ArrowRight/><div><b>{results.length+15}</b><span>match your filters</span></div><ArrowRight/><div className="highlight"><Check/><b>{results.length}</b><span>feasible right now</span></div><ArrowRight/><div><Sparkles/><b>Top picks</b><span>personalized for you</span></div></section>
 <section className="resultsHead"><div><span className="eyebrow">CURATED FOR THIS MOMENT</span><h2>Experiences that <i>actually fit</i></h2><p>Ranked by preferences, travel time, schedule, price, availability and local relevance.</p></div><button className="filter">{ctx.isRaining?"Indoor, rain-ready":"All feasible"} <ArrowRight size={15}/></button></section>
 <section className="grid">{results.map((r,i)=><article className="card" key={r.experience.id}><div className="photo" style={{backgroundImage:`url(${r.experience.image})`}}><span>{r.experience.category}</span><button onClick={()=>setSaved(x=>x.includes(r.experience.id)?x.filter(y=>y!==r.experience.id):[...x,r.experience.id])}><Bookmark size={17} fill={saved.includes(r.experience.id)?"currentColor":"none"}/></button><div className="match">{r.match}% <small>match</small></div></div><div className="cardbody"><div className="titleline"><h3>{r.experience.title}</h3><span>★ {r.experience.rating}</span></div><p className="area"><MapPin size={14}/>{r.experience.area} · {r.experience.distance.toFixed(1)} km away</p><div className="facts"><span>{money(r.experience.price)}</span><span>{r.experience.duration} min</span><span>{r.experience.travelMinutes} min travel</span></div><div className="fit"><Check size={15}/><b>Fits your {ctx.timeAvailable}-min window</b><span>{r.feasibility.totalMinutes} min total</span></div><ul>{r.reasons.slice(0,3).map(x=><li key={x}><Check size={13}/>{x}</li>)}</ul><div className="cardactions"><button className="textbtn">View details</button><button className="add" onClick={()=>add(r.experience.id)}>{plan.includes(r.experience.id)?<><Check size={15}/> Added</>:<><CalendarPlus size={15}/> Add to itinerary</>}</button></div></div></article>)}</section>
 <section className="trust"><Sparkles/><div><b>Why these feel different</b><span>Every result has passed availability, group, distance, budget and door-to-door schedule checks. Demo availability is mock data, last synced moments ago.</span></div></section>{toast&&<div className="toast"><Check size={16}/>{toast}</div>}</main>
}
function Provider({onBack}:{onBack:()=>void}){return <main><nav><div className="brand"><Compass size={21}/> roamly <small>for providers</small></div><button className="providerBtn" onClick={onBack}>← Back to discovery</button></nav><section className="providerHero"><span className="eyebrow">PROVIDER INTELLIGENCE</span><h1>Your next best<br/><i>guest is nearby.</i></h1><p>Turn local demand signals into better availability, pricing and moments that matter.</p></section><section className="metrics"><div><span>Profile views</span><b>1,284</b><em>↑ 18% this week</em></div><div><span>High-intent matches</span><b>326</b><em>↑ 24% this week</em></div><div><span>Conversion potential</span><b>₹48.9K</b><em>next 7 days</em></div></section><section className="providerGrid"><article className="demand"><span className="eyebrow">MUMBAI POTTERY WORKSHOP</span><h2>Demand is <i>high</i> for your experience.</h2><p>Travelers matching your offer are looking for a calm, indoor cultural activity this weekend.</p><div className="bars"><label>Saturday <b>92%</b><i style={{width:"92%"}}/></label><label>Sunday <b>76%</b><i style={{width:"76%"}}/></label><label>Weekday evenings <b>64%</b><i style={{width:"64%"}}/></label></div><div className="suggestion"><Sparkles/><span><b>Suggested action</b> Add 4 Saturday slots from 5–8 PM to capture the highest local-cultural demand.</span></div></article><article className="segments"><span className="eyebrow">WHO IS LOOKING</span><h2>High-demand segments</h2>{[["Cultural explorers","42%"],["Couples","31%"],["International visitors","18%"]].map(([x,n])=><div className="segment" key={x}><span>{x}</span><b>{n}</b></div>)}<hr/><span>Most requested price range</span><h3>₹800 – ₹1,500</h3><span>Popular booking window</span><h3>5 PM – 8 PM</h3></article></section></main>}
